title: Praktyczny EE.09
description: Rozwiązania arkuszy praktycznych z egzaminu zawodowego na technika informatyka [kwalifikacja EE.09]
show_downloads: true
google_analytics: <script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-XXXXX-Y', 'auto');
ga('send', 'pageview');
</script>
theme: jekyll-theme-cayman
